Repository drevops/vortex, pull requests merged in 2021-08, with the labels that each got.

#640 [7.x] Fixed tests.
  README.md
  scripts/drevops/tests/bats/workflow1.bats
Labels: 7.x

#639 Updated tests and added ahoy fei.
  .ahoy.yml
  README.md
  phpcs.xml
  scripts/drevops/tests/bats/_helper_drevops.bash
  scripts/drevops/tests/bats/_helper_drevops_workflow.bash
  scripts/drevops/tests/bats/workflow0.bats
  scripts/drevops/tests/bats/workflow1.bats
Labels: 8.x

#643 [7.x] Updated to Composer 2.
  .docker/Dockerfile.cli
Labels: 7.x

#649 [8.x] Updated config for Lagoon.
  .circleci/config.yml
  .github/workflows/dispatch-webhook-lagoon.yml
  .lagoon.yml
  docroot/sites/default/settings.php
  install.php
  scripts/drevops/deploy-lagoon.sh
  scripts/drevops/download-db-lagoon.sh
  scripts/drevops/download-db.sh
  scripts/drevops/drupal-export-db.sh
  scripts/drevops/notify-deployment.php
  scripts/drevops/tests/bats/_helper_drevops.bash
Labels: 8.x

#650 [7.x] Updated config for Lagoon.
  .circleci/config.yml
  .github/workflows/dispatch-webhook-lagoon.yml
  .lagoon.yml
  install.php
  scripts/drevops/deploy-lagoon.sh
  scripts/drevops/download-db-lagoon.sh
  scripts/drevops/download-db.sh
  scripts/drevops/notify-deployment.php
  scripts/drevops/tests/bats/_helper_drevops.bash
Labels: 7.x

#651 [9.x] Porting D8 do D9.
  .circleci/config.yml
  .env
  README.md
  composer.json
  dependencies.yml
  docroot/modules/custom/your_site_core/tests/src/Functional/YourSiteCoreFunctionalTestBase.php
  docroot/modules/custom/your_site_core/your_site_core.info.yml
  docroot/modules/custom/your_site_core/your_site_core.install
  docroot/profiles/custom/your_site_profile/your_site_profile.info.yml
  docroot/robots.txt
  docroot/sites/default/default.services.yml
  docroot/sites/default/default.settings.php
  docroot/themes/custom/your_site_theme/your_site_theme.info.yml
  docroot/update.php
  install.php
  install.sh
  scripts/drevops/doctor.sh
  scripts/drevops/drupal-install-site.sh
  scripts/drevops/tests/bats/_helper_drevops.bash
  scripts/drevops/tests/bats/_helper_drevops_workflow.bash
  scripts/drevops/tests/bats/install_initial.bats
  scripts/drevops/tests/bats/workflow1.bats
Labels: 9.x

#654 [9.x] Added composer cmd to ahoy.
  .ahoy.yml
  scripts/drevops/tests/bats/_helper_drevops_workflow.bash
  scripts/drevops/tests/bats/workflow0.bats
Labels: enhancement, 9.x, needs review

#656 Fixed ahoy pull-db not logging into the DockerHub automatically.
  .ahoy.yml
  .env
  default.env.local
  scripts/drevops/docker-login.sh
  scripts/drevops/tests/bats/workflow1.bats
Labels: 7.x
