Repository drevops/vortex, pull requests merged in 2024-04, with the labels that each got.

#1254 Updated drevops/mariadb-drupal-data to 24.3.0.
  .circleci/config.yml
Labels: Type: Chore, PR: Ready to be merged

#1257 [#736] Added tests for `webhook` and `docker` deployment.
  .scaffold/tests/bats/_helper.deployment.bash
  .scaffold/tests/bats/deploy-docker.bats
  .scaffold/tests/bats/deployment-webhook.bats
  .scaffold/tests/bats/login-docker.bats
Labels: PR: Needs review

#1276 [#768] Added checking for bin existence in scripts.
  scripts/drevops/deploy-docker.sh
  scripts/drevops/deploy-lagoon.sh
  scripts/drevops/deploy-webhook.sh
  scripts/drevops/doctor.sh
  scripts/drevops/download-db-acquia.sh
  scripts/drevops/download-db-curl.sh
  scripts/drevops/download-db-docker-registry.sh
  scripts/drevops/download-db-ftp.sh
  scripts/drevops/download-db-lagoon.sh
  scripts/drevops/export-db-docker.sh
  scripts/drevops/export-db.sh
  scripts/drevops/github-labels.sh
  scripts/drevops/login-docker.sh
  scripts/drevops/mirror-code.sh
  scripts/drevops/notify-github.sh
  scripts/drevops/notify-jira.sh
  scripts/drevops/notify-newrelic.sh
  scripts/drevops/reset.sh
  scripts/drevops/setup-ssh.sh
  scripts/drevops/task-copy-db-acquia.sh
  scripts/drevops/task-copy-files-acquia.sh
  scripts/drevops/task-custom-lagoon.sh
  scripts/drevops/task-purge-cache-acquia.sh
  scripts/drevops/update-scaffold.sh
Labels: PR: Ready to be merged

#1295 [#1293] Simplified `DREVOPS_DB_DOCKER_IMAGE` to `DREVOPS_DB_IMAGE`.
  .ahoy.yml
  .circleci/config.yml
  .env
  .scaffold/docs/.utils/variables/extra/.env.variables.sh
  .scaffold/docs/content/workflows/variables.mdx
  .scaffold/tests/bats/_helper.bash
  .scaffold/tests/bats/docker-compose.bats
  .scaffold/tests/bats/install.initial.bats
  .scaffold/tests/bats/workflow.storage.curl.bats
  .scaffold/tests/bats/workflow.storage.image.bats
  .scaffold/tests/bats/workflow.storage.image_cached.bats
  docker-compose.yml
  scripts/drevops/download-db-docker-registry.sh
  scripts/drevops/download-db.sh
  scripts/drevops/export-db.sh
  scripts/drevops/info.sh
  scripts/drevops/provision.sh
Labels: PR: AUTOMERGE

#1299 [#1297] Updated to `mariadb-10.11-drupal` image.
  .docker/mariadb.dockerfile
  .scaffold/tests/bats/fixtures/docker-compose.env.json
  .scaffold/tests/bats/fixtures/docker-compose.env_local.json
  .scaffold/tests/bats/fixtures/docker-compose.noenv.json
  docker-compose.yml
Labels: PR: URGENT
