Repository drevops/vortex, pull requests merged in 2025-05, with the labels that each got.

#1619 Minor installer fixes.
  .vortex/installer/src/Command/InstallCommand.php
  .vortex/installer/src/Utils/Downloader.php
  .vortex/installer/src/Utils/File.php
  .vortex/installer/src/Utils/Strings.php
  .vortex/installer/src/Utils/Tui.php
  .vortex/installer/tests/Functional/FunctionalTestCase.php
  .vortex/installer/tests/Unit/StringsTest.php
Labels: PR: Needs review

#1625 [#1610] Replaced Redis with Valkey.
  .ahoy.yml
  .env
  .vortex/docs/content/drupal/README.mdx
  .vortex/docs/content/getting-started/features.mdx
  .vortex/docs/content/tools/docker.mdx
  .vortex/docs/content/workflows/variables.mdx
  .vortex/docs/cspell.json
  .vortex/installer/src/Prompts/Handlers/Services.php
  .vortex/installer/src/Prompts/PromptManager.php
  .vortex/installer/tests/Fixtures/install/_baseline/.ahoy.yml
  .vortex/installer/tests/Fixtures/install/_baseline/.env
  .vortex/installer/tests/Fixtures/install/_baseline/docker-compose.yml
  .vortex/installer/tests/Fixtures/install/_baseline/tests/phpunit/Drupal/SettingsTestCase.php
  .vortex/installer/tests/Fixtures/install/_baseline/tests/phpunit/Drupal/SwitchableSettingsTest.php
  .vortex/installer/tests/Fixtures/install/_baseline/web/sites/default/includes/modules/settings.redis.php
  .vortex/installer/tests/Fixtures/install/hosting_acquia/docroot/sites/default/includes/modules/settings.redis.php
  .vortex/installer/tests/Fixtures/install/hosting_lagoon/docker-compose.yml
  .vortex/installer/tests/Fixtures/install/services_no_clamav/.env
  .vortex/installer/tests/Fixtures/install/services_no_solr/docker-compose.yml
  .vortex/installer/tests/Fixtures/install/services_no_valkey/.ahoy.yml
  .vortex/installer/tests/Fixtures/install/services_no_valkey/.env
  .vortex/installer/tests/Fixtures/install/services_no_valkey/composer.json
  .vortex/installer/tests/Fixtures/install/services_no_valkey/docker-compose.yml
  .vortex/installer/tests/Fixtures/install/services_no_valkey/scripts/custom/provision-10-example.sh
  .vortex/installer/tests/Fixtures/install/services_no_valkey/tests/phpunit/Drupal/SwitchableSettingsTest.php
  .vortex/installer/tests/Fixtures/install/services_no_valkey/web/sites/default/includes/modules/-settings.redis.php
  .vortex/installer/tests/Fixtures/install/services_none/.ahoy.yml
  .vortex/installer/tests/Fixtures/install/services_none/.env
  .vortex/installer/tests/Fixtures/install/services_none/docker-compose.yml
  .vortex/installer/tests/Fixtures/install/services_none/tests/phpunit/Drupal/SwitchableSettingsTest.php
  .vortex/installer/tests/Fixtures/version_replacement/baseline/docker-compose.yml
  .vortex/installer/tests/Fixtures/version_replacement/expected/docker-compose.yml
  .vortex/installer/tests/Functional/FunctionalTestCase.php
  .vortex/installer/tests/Functional/InstallTest.php
  .vortex/installer/tests/Unit/PromptManagerTest.php
  .vortex/tests/bats/_helper.workflow.bash
  .vortex/tests/bats/docker-compose.bats
  .vortex/tests/bats/fixtures/docker-compose.env.json
  .vortex/tests/bats/fixtures/docker-compose.env_local.json
  .vortex/tests/bats/fixtures/docker-compose.env_mod.json
  .vortex/tests/bats/fixtures/docker-compose.noenv.json
  .vortex/tests/bats/workflow.install.db.bats
  docker-compose.yml
  scripts/custom/provision-10-example.sh
  tests/phpunit/Drupal/SettingsTestCase.php
  tests/phpunit/Drupal/SwitchableSettingsTest.php
  web/sites/default/includes/modules/settings.redis.php
Labels: PR: Ready to be merged

#1628 #1623: updated drupal badge in README.dist.md - d10 to d11
  .vortex/installer/tests/Fixtures/install/_baseline/README.md
  .vortex/installer/tests/Fixtures/install/ciprovider_circleci/README.md
  .vortex/installer/tests/Fixtures/install/deploy_type_all_circleci/README.md
  .vortex/installer/tests/Fixtures/install/deploy_type_none_circleci/README.md
  .vortex/installer/tests/Fixtures/install/deps_updates_provider_ci_circleci/README.md
  .vortex/installer/tests/Fixtures/install/deps_updates_provider_none/README.md
  .vortex/installer/tests/Fixtures/install/names/README.md
  README.dist.md
Labels: PR: Ready to be merged

#1629 Updated CI Runner to 25.5.0.
  .circleci/config.yml
  .github/workflows/build-test-deploy.yml
  .github/workflows/vortex-test-common.yml
Labels: PR: DO NOT MERGE

#1634 [#1612] Updated badge color in README.dist.md
  .vortex/installer/tests/Fixtures/install/_baseline/README.md
  .vortex/installer/tests/Fixtures/install/deps_updates_provider_none/README.md
  .vortex/installer/tests/Fixtures/install/preserve_docs_onboarding_disabled/README.md
  .vortex/installer/tests/Unit/PromptManagerTest.php
  .vortex/tests/bats/_helper.bash
  README.dist.md
Labels: PR: Needs review

#1635 [#1611]: SecKit update + tests.
  .vortex/README.md
  .vortex/installer/tests/Fixtures/install/_baseline/tests/phpunit/Drupal/EnvironmentSettingsTest.php
  .vortex/installer/tests/Fixtures/install/_baseline/web/sites/default/includes/modules/settings.seckit.php
  .vortex/installer/tests/Fixtures/install/hosting_acquia/docroot/sites/default/includes/modules/settings.seckit.php
  .vortex/installer/tests/Fixtures/install/hosting_acquia/tests/phpunit/Drupal/EnvironmentSettingsTest.php
  .vortex/installer/tests/Fixtures/install/hosting_lagoon/tests/phpunit/Drupal/EnvironmentSettingsTest.php
  tests/phpunit/Drupal/EnvironmentSettingsTest.php
  web/sites/default/includes/modules/settings.seckit.php
Labels: PR: Needs review

#1638 [#1609]: Added `DRUPAL_SHIELD_DISABLED` variable.
  .vortex/installer/tests/Fixtures/install/_baseline/tests/phpunit/Drupal/SwitchableSettingsTest.php
  .vortex/installer/tests/Fixtures/install/_baseline/web/sites/default/includes/modules/settings.shield.php
  .vortex/installer/tests/Fixtures/install/hosting_acquia/docroot/sites/default/includes/modules/settings.shield.php
  tests/phpunit/Drupal/SwitchableSettingsTest.php
  web/sites/default/includes/modules/settings.shield.php
Labels: PR: AUTOMERGE

#1640 [#1556]: Renamed config_split `test` to `stage`.
  .vortex/installer/tests/Fixtures/install/_baseline/config/stage/.gitkeep
  .vortex/installer/tests/Fixtures/install/_baseline/config/stage/.htaccess
  .vortex/installer/tests/Fixtures/install/_baseline/tests/phpunit/Drupal/SwitchableSettingsTest.php
  .vortex/installer/tests/Fixtures/install/_baseline/web/sites/default/includes/modules/settings.config_split.php
  .vortex/installer/tests/Fixtures/install/hosting_acquia/docroot/sites/default/includes/modules/settings.config_split.php
  .vortex/installer/tests/Fixtures/install/hosting_acquia/tests/phpunit/Drupal/EnvironmentSettingsTest.php
  .vortex/installer/tests/Fixtures/install/hosting_lagoon/tests/phpunit/Drupal/EnvironmentSettingsTest.php
  .vortex/tests/bats/_helper.bash
  config/stage/.gitkeep
  config/stage/.htaccess
  tests/phpunit/Drupal/EnvironmentSettingsTest.php
  tests/phpunit/Drupal/SwitchableSettingsTest.php
  web/sites/default/includes/modules/settings.config_split.php
Labels: PR: AUTOMERGE

#1648 Updated TWIG CS fixer class.
  .twig-cs-fixer.php
  .vortex/installer/tests/Fixtures/install/_baseline/.twig-cs-fixer.php
Labels: PR: Needs review

#1645 [#1608] Fixed Renovate schedule for contribs.
  .vortex/installer/tests/Fixtures/install/_baseline/renovate.json
  renovate.json
Labels: PR: Requires more work

#1641 [#1620]: Added skip deployment env variable.
  .github/workflows/build-test-deploy.yml
  .vortex/docs/.utils/variables/extra/ci.variables.sh
  .vortex/docs/content/workflows/deployment.mdx
  .vortex/docs/content/workflows/variables.mdx
  .vortex/installer/tests/Fixtures/install/_baseline/.github/workflows/build-test-deploy.yml
  .vortex/installer/tests/Fixtures/install/deploy_type_none_gha/.github/workflows/build-test-deploy.yml
  .vortex/installer/tests/Fixtures/install/hosting_acquia/docs/deployment.md
  .vortex/installer/tests/Fixtures/install/hosting_lagoon/docs/deployment.md
  .vortex/tests/bats/_helper.deployment.bash
  .vortex/tests/bats/deploy-artifact.bats
  docs/deployment.md
  scripts/vortex/deploy.sh
Labels: PR: Needs review
